### ISSUE TITLE
Generating and exporting Eurostat quality report 

### ISSUE THREAD

**Issue by merangelik** [jdemetra/rjdemetra#35]
Hi,

[as my colleague mentioned](https://github.com/nbbrd/rjdemetra/issues/30), we are currently developing an [R package that builds on top of RJDemetra](https://github.com/statistikat/persephone). 

In this context, I would like to ask if by any chance you are planning on incorporating a function that generates a SA quality report for Eurostat and exports it to a csv - as is possible with JDemetra+?

**Comment by AQLT** [comment]
Hi,
For the moment, the goal of the package is to only perform to seasonal adjustment. Other SA topics (benchmarking, quality reports, direct vs indirect SA, etc.) are not planned to be added in RJDemetra but they might be in other packages. That's why we are not planning to add SA quality reports in this package but it could be a good idea to create another one with this option.
